image: gitpod/workspace-full:latest


ports:
- port: 3000
onOpen: open-preview
- port: 3001
onOpen: ignore


tasks:
- init: |
sudo apt-get update
sudo apt-get install -y docker.io
sudo service docker start || true
mkdir -p /workspace/chrome-config
sudo docker pull lscr.io/linuxserver/chrome:latest || true
command: |
# remove any stale container
sudo docker rm -f chrome || true


# run the Chrome container detached
sudo docker run -d \
--name=chrome \
--security-opt seccomp=unconfined \
-e PUID=1000 \
-e PGID=1000 \
-e TZ=Etc/UTC \
-p 3000:3000 \
-p 3001:3001 \
-v /workspace/chrome-config:/config \
--shm-size=1gb \
lscr.io/linuxserver/chrome:latest || true


echo "✅ linuxserver/chrome started (ports 3000 and 3001). If the preview didn't open, open port 3000 in the Gitpod ports view."


vscode:
extensions:
- ms-azuretools.vscode-docker


# Optional: run the workspace in headless mode without blocking the terminal
projects:
- name: gitpod-linuxserver-chrome
